name: Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.3.0
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Generate HTML report
      run: npm run build

    - name: Deploy HTML report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
