
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: main
  workflow_dispatch:

name: Render Report


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download and use.
 
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
               any::knitr
               any::readr
               any::lubridate
               ant::ggplot2
               any::tidyverse
               any::googledrive

      - name: Render document
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: report.qmd

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
