name: ICU Sepsis Status Report
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build ICU Status Report
        run: |
          # Add commands here to build your ICU status report
          # and output it to a file called "ICUSepsisreport.html"
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: ICU Sepsis Status Report HTML
          path: report.html
